stages:
  - test
  - deploy

image: node:10

before_script:
  - npm ci --silent

test:
  stage: test
  script:
    - npm run test
  cache:
    key: "waxing" # universal cache
    paths:
      - /root/.npm
