stages:
  - test
  - deploy

image: node:10

before_script:
  - npm ci --cache .npm --prefer-offline

cache:
  key: "waxing" # universal cache
  paths:
    - .npm/

test:
  stage: test
  script:
    - npm run coverage
  artifacts:
    name: "png2icon_coverage_${CI_BUILD_ID}_${CI_BUILD_REF}"
    when: always
    expire_in: 6 mos
    reports:
      junit: report.xml
    paths:
      - coverage/
