stages:
  - test
  - deploy

image: node:10

before_script:
  - npm ci --silent

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npm run build
    - npm publish
  only:
    - tags
  allow_failure: false
